[package]
name = "torchat-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
async-trait = "0.1.74"
chacha20poly1305 = "0.10.1"
chrono = "0.4.31"
circular-queue = "0.2.6"
clap = { version = "4.4.6", features = ["cargo", "derive"] }
crossterm = { version = "0.27.0", features = ["event-stream"] }
ed25519-dalek = { version = "2.0.0", features = ["pkcs8"] }
futures = "0.3.28"
futures-lite = "1.13.0"
hex = "0.4.3"
hkdf = "0.12.3"
lazy_static = "1.4.0"
log = "0.4.20"
ratatui = "0.23.0"
serde = { version = "1.0.188", features = ["derive"] }
serde_cbor = "0.11.2"
sha2 = "0.10.8"
tokio = { version = "1.32.0", features = ["full"] }
tokio-serde = { version = "0.8.0", features = ["cbor"] }
tokio-socks = "0.5.1"
tokio-util = { version = "0.7.9", features = ["codec"] }
tor-client-lib = { git = "https://github.com/jacklund/tor-client-lib.git", version = "0.1.0" }
unicode-width = "0.1.11"
x25519-dalek = { version = "2.0.0", features = ["getrandom"] }
