[package]
name = "torchat-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
chrono = "0.4.31"
circular-queue = "0.2.6"
clap = { version = "4.4.6", features = ["cargo", "derive"] }
crossterm = { version = "0.27.0", features = ["event-stream"] }
futures = "0.3.28"
futures-lite = "1.13.0"
log = "0.4.20"
tokio = { version = "1.32.0", features = ["full"] }
tokio-util = { version = "0.7.9", features = ["codec"] }
tor-client-lib = { git = "https://github.com/jacklund/tor-client-lib.git", version = "0.1.0" }
tui = "0.19.0"
unicode-width = "0.1.11"
